"""empty message

Revision ID: 512a625d4f1e
Revises: 4d88c3bface8
Create Date: 2021-06-06 19:20:14.209274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512a625d4f1e'
down_revision = '4d88c3bface8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
