"""empty message

Revision ID: d5d792e08964
Revises: a03c8e544452
Create Date: 2021-06-07 03:48:39.383879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d792e08964'
down_revision = 'a03c8e544452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
